user_num = int(input('Enter integer:\n'))
print("You entered:",user_num)
print(user_num, "squared is", user_num*user_num)
print("And",user_num,"cubed is",user_num**3,"!!")
n=int(input("Enter another integer:\n"))
print(user_num,"+",n,"is",user_num+n)
print(user_num,"*",n,"is",user_num*n)